 # Gemini CLI Configuration
# This configuration is designed to allow full autonomy within the CLI tool.

# General Settings
autonomy: true  # Enable full autonomy for operations
allow_file_management: true  # Allow file and folder management operations
allow_network_interactions: true  # Permit network requests

# Command Settings
commands:
enable_file_commands:
  copy: true  # Allow copying of files
  move: true  # Allow moving of files
  delete: true  # Allow deleting of files
  create: true  # Allow creating new files and directories
  modify: true  # Allow modifying existing files

enable_network_commands:
  fetch: true  # Allow fetching remote resources
  upload: true  # Allow uploading files to a server
  download: true  # Allow downloading files from a server

# Security Settings
security:
  enable_logging: true  # Enable command logging for auditing purposes
  notification_on_action: true  # Notify users on significant actions (e.g., file deletion)

# User Experience
user_interface:
  enable_interactive_mode: true  # Allow interactive command session
  display_help_messages: true  # Show help messages for commands
